<?php
/**
 * DSWorkflowComparisonOperatorTypes
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DocuSign\Maestro
 * @author   Swagger Codegen team <apihelp@docusign.com>
 * @license  The DocuSign PHP Client SDK is licensed under the MIT License.
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Maestro API
 *
 * Maestro authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * OpenAPI spec version: 1.0.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DocuSign\Maestro\Model;
use DocuSign\Maestro\ObjectSerializer;

/**
 * DSWorkflowComparisonOperatorTypes Class Doc Comment
 *
 * @category    Class
 * @package     DocuSign\Maestro
 * @author      Swagger Codegen team <apihelp@docusign.com>
 * @license     The DocuSign PHP Client SDK is licensed under the MIT License.
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DSWorkflowComparisonOperatorTypes
{
    /**
     * Possible values of this enum
     */
    const CONTAINS = 'Contains';
    const NOT_CONTAINS = 'NotContains';
    const EQUAL = 'Equal';
    const NOT_EQUAL = 'NotEqual';
    const GREATER_THAN = 'GreaterThan';
    const GREATER_THAN_OR_EQUAL = 'GreaterThanOrEqual';
    const LESS_THAN = 'LessThan';
    const LESS_THAN_OR_EQUAL = 'LessThanOrEqual';
    const STARTS_WITH = 'StartsWith';
    const NOT_STARTS_WITH = 'NotStartsWith';
    const ENDS_WITH = 'EndsWith';
    const NOT_ENDS_WITH = 'NotEndsWith';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CONTAINS,
            self::NOT_CONTAINS,
            self::EQUAL,
            self::NOT_EQUAL,
            self::GREATER_THAN,
            self::GREATER_THAN_OR_EQUAL,
            self::LESS_THAN,
            self::LESS_THAN_OR_EQUAL,
            self::STARTS_WITH,
            self::NOT_STARTS_WITH,
            self::ENDS_WITH,
            self::NOT_ENDS_WITH,
        ];
    }
}

