<?php
/**
 * ErrorCodes
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DocuSign\Maestro
 * @author   Swagger Codegen team <apihelp@docusign.com>
 * @license  The DocuSign PHP Client SDK is licensed under the MIT License.
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Maestro API
 *
 * Maestro authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * OpenAPI spec version: 1.0.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DocuSign\Maestro\Model;
use DocuSign\Maestro\ObjectSerializer;

/**
 * ErrorCodes Class Doc Comment
 *
 * @category    Class
 * @description Internal Error Codes
 * @package     DocuSign\Maestro
 * @author      Swagger Codegen team <apihelp@docusign.com>
 * @license     The DocuSign PHP Client SDK is licensed under the MIT License.
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ErrorCodes
{
    /**
     * Possible values of this enum
     */
    const _10001 = 'ERR_10001';
    const _10002 = 'ERR_10002';
    const _10003 = 'ERR_10003';
    const _10004 = 'ERR_10004';
    const _10005 = 'ERR_10005';
    const _10006 = 'ERR_10006';
    const _10007 = 'ERR_10007';
    const _10008 = 'ERR_10008';
    const _10009 = 'ERR_10009';
    const _10101 = 'ERR_10101';
    const _10201 = 'ERR_10201';
    const _10202 = 'ERR_10202';
    const _10301 = 'ERR_10301';
    const _10302 = 'ERR_10302';
    const _10401 = 'ERR_10401';
    const _10801 = 'ERR_10801';
    const _10802 = 'ERR_10802';
    const _10999 = 'ERR_10999';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_10001,
            self::_10002,
            self::_10003,
            self::_10004,
            self::_10005,
            self::_10006,
            self::_10007,
            self::_10008,
            self::_10009,
            self::_10101,
            self::_10201,
            self::_10202,
            self::_10301,
            self::_10302,
            self::_10401,
            self::_10801,
            self::_10802,
            self::_10999,
        ];
    }
}

