<?php
/**
 * NewOrUpdatedWorkflowDefinitionResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DocuSign\Maestro
 * @author   Swagger Codegen team <apihelp@docusign.com>
 * @license  The DocuSign PHP Client SDK is licensed under the MIT License.
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Maestro API
 *
 * Maestro authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * OpenAPI spec version: 1.0.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DocuSign\Maestro\Model;

use \ArrayAccess;
use DocuSign\Maestro\ObjectSerializer;

/**
 * NewOrUpdatedWorkflowDefinitionResponse Class Doc Comment
 *
 * @category    Class
 * @package     DocuSign\Maestro
 * @author      Swagger Codegen team <apihelp@docusign.com>
 * @license     The DocuSign PHP Client SDK is licensed under the MIT License.
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NewOrUpdatedWorkflowDefinitionResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'NewOrUpdatedWorkflowDefinitionResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'is_valid_workflow_definition' => '?bool',
        'validation_errors' => '\DocuSign\Maestro\Model\ValidationErrors[]',
        'workflow_definition' => '\DocuSign\Maestro\Model\WorkflowDefinition',
        'workflow_definition_id' => '?string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'is_valid_workflow_definition' => null,
        'validation_errors' => null,
        'workflow_definition' => null,
        'workflow_definition_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'is_valid_workflow_definition' => 'isValidWorkflowDefinition',
        'validation_errors' => 'validationErrors',
        'workflow_definition' => 'workflowDefinition',
        'workflow_definition_id' => 'workflowDefinitionId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'is_valid_workflow_definition' => 'setIsValidWorkflowDefinition',
        'validation_errors' => 'setValidationErrors',
        'workflow_definition' => 'setWorkflowDefinition',
        'workflow_definition_id' => 'setWorkflowDefinitionId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'is_valid_workflow_definition' => 'getIsValidWorkflowDefinition',
        'validation_errors' => 'getValidationErrors',
        'workflow_definition' => 'getWorkflowDefinition',
        'workflow_definition_id' => 'getWorkflowDefinitionId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['is_valid_workflow_definition'] = isset($data['is_valid_workflow_definition']) ? $data['is_valid_workflow_definition'] : null;
        $this->container['validation_errors'] = isset($data['validation_errors']) ? $data['validation_errors'] : null;
        $this->container['workflow_definition'] = isset($data['workflow_definition']) ? $data['workflow_definition'] : null;
        $this->container['workflow_definition_id'] = isset($data['workflow_definition_id']) ? $data['workflow_definition_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['is_valid_workflow_definition'] === null) {
            $invalidProperties[] = "'is_valid_workflow_definition' can't be null";
        }
        if ($this->container['validation_errors'] === null) {
            $invalidProperties[] = "'validation_errors' can't be null";
        }
        if ($this->container['workflow_definition'] === null) {
            $invalidProperties[] = "'workflow_definition' can't be null";
        }
        if ($this->container['workflow_definition_id'] === null) {
            $invalidProperties[] = "'workflow_definition_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets is_valid_workflow_definition
     *
     * @return ?bool
     */
    public function getIsValidWorkflowDefinition()
    {
        return $this->container['is_valid_workflow_definition'];
    }

    /**
     * Sets is_valid_workflow_definition
     *
     * @param ?bool $is_valid_workflow_definition is_valid_workflow_definition
     *
     * @return $this
     */
    public function setIsValidWorkflowDefinition($is_valid_workflow_definition)
    {
        $this->container['is_valid_workflow_definition'] = $is_valid_workflow_definition;

        return $this;
    }

    /**
     * Gets validation_errors
     *
     * @return \DocuSign\Maestro\Model\ValidationErrors[]
     */
    public function getValidationErrors()
    {
        return $this->container['validation_errors'];
    }

    /**
     * Sets validation_errors
     *
     * @param \DocuSign\Maestro\Model\ValidationErrors[] $validation_errors validation_errors
     *
     * @return $this
     */
    public function setValidationErrors($validation_errors)
    {
        $this->container['validation_errors'] = $validation_errors;

        return $this;
    }

    /**
     * Gets workflow_definition
     *
     * @return \DocuSign\Maestro\Model\WorkflowDefinition
     */
    public function getWorkflowDefinition()
    {
        return $this->container['workflow_definition'];
    }

    /**
     * Sets workflow_definition
     *
     * @param \DocuSign\Maestro\Model\WorkflowDefinition $workflow_definition workflow_definition
     *
     * @return $this
     */
    public function setWorkflowDefinition($workflow_definition)
    {
        $this->container['workflow_definition'] = $workflow_definition;

        return $this;
    }

    /**
     * Gets workflow_definition_id
     *
     * @return ?string
     */
    public function getWorkflowDefinitionId()
    {
        return $this->container['workflow_definition_id'];
    }

    /**
     * Sets workflow_definition_id
     *
     * @param ?string $workflow_definition_id workflow_definition_id
     *
     * @return $this
     */
    public function setWorkflowDefinitionId($workflow_definition_id)
    {
        $this->container['workflow_definition_id'] = $workflow_definition_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

