<?php
/**
 * StartedByInstance
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DocuSign\Maestro
 * @author   Swagger Codegen team <apihelp@docusign.com>
 * @license  The DocuSign PHP Client SDK is licensed under the MIT License.
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Maestro API
 *
 * Maestro authors and executes experiences that allow non-coders the ability to define Simple Business Process without having to write code and to deploy them seamlessly without having to have development expertise
 *
 * OpenAPI spec version: 1.0.0
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DocuSign\Maestro\Model;

use \ArrayAccess;
use DocuSign\Maestro\ObjectSerializer;

/**
 * StartedByInstance Class Doc Comment
 *
 * @category    Class
 * @description The started by information for a workflow instance
 * @package     DocuSign\Maestro
 * @author      Swagger Codegen team <apihelp@docusign.com>
 * @license     The DocuSign PHP Client SDK is licensed under the MIT License.
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StartedByInstance implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'StartedByInstance';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'started_by_id' => '?string',
        'started_by_name' => '?string',
        'started_by_type' => '?string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'started_by_id' => null,
        'started_by_name' => null,
        'started_by_type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'started_by_id' => 'startedById',
        'started_by_name' => 'startedByName',
        'started_by_type' => 'startedByType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'started_by_id' => 'setStartedById',
        'started_by_name' => 'setStartedByName',
        'started_by_type' => 'setStartedByType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'started_by_id' => 'getStartedById',
        'started_by_name' => 'getStartedByName',
        'started_by_type' => 'getStartedByType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const STARTED_BY_TYPE_ANONYMOUS = 'Anonymous';
    const STARTED_BY_TYPE_PREPARER = 'Preparer';
    const STARTED_BY_TYPE_PARTICIPANT = 'Participant';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStartedByTypeAllowableValues()
    {
        return [
            self::STARTED_BY_TYPE_ANONYMOUS,
            self::STARTED_BY_TYPE_PREPARER,
            self::STARTED_BY_TYPE_PARTICIPANT,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['started_by_id'] = isset($data['started_by_id']) ? $data['started_by_id'] : null;
        $this->container['started_by_name'] = isset($data['started_by_name']) ? $data['started_by_name'] : null;
        $this->container['started_by_type'] = isset($data['started_by_type']) ? $data['started_by_type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getStartedByTypeAllowableValues();
        if (!is_null($this->container['started_by_type']) && !in_array($this->container['started_by_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'started_by_type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets started_by_id
     *
     * @return ?string
     */
    public function getStartedById()
    {
        return $this->container['started_by_id'];
    }

    /**
     * Sets started_by_id
     *
     * @param ?string $started_by_id started_by_id
     *
     * @return $this
     */
    public function setStartedById($started_by_id)
    {
        $this->container['started_by_id'] = $started_by_id;

        return $this;
    }

    /**
     * Gets started_by_name
     *
     * @return ?string
     */
    public function getStartedByName()
    {
        return $this->container['started_by_name'];
    }

    /**
     * Sets started_by_name
     *
     * @param ?string $started_by_name The user name of the person who starts a workflow Instance
     *
     * @return $this
     */
    public function setStartedByName($started_by_name)
    {
        $this->container['started_by_name'] = $started_by_name;

        return $this;
    }

    /**
     * Gets started_by_type
     *
     * @return ?string
     */
    public function getStartedByType()
    {
        return $this->container['started_by_type'];
    }

    /**
     * Sets started_by_type
     *
     * @param ?string $started_by_type started_by_type
     *
     * @return $this
     */
    public function setStartedByType($started_by_type)
    {
        $allowedValues = $this->getStartedByTypeAllowableValues();
        if (!is_null($started_by_type) && !in_array($started_by_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'started_by_type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['started_by_type'] = $started_by_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

